### PR TITLE
Allow Git pushes without tracking branch.

### PR DESCRIPTION
**Pull request by jakehschwartz**
- Default remote is 'origin'

### CODE REVIEW

**Comment by jroper** [comment]
I'm not sure about this - remote tracking branches are the git way of specifying what the default should be, so that you don't need to hard code conventions like `origin` into tools. Setting the remote tracking branch only needs to be done once, and it's often done automatically when you checkout a branch. I don't think we should be undermining gits inbuilt mechanism for specifying defaults - I think failing when there's no default configured is the right behaviour, this gets people to do the right, git way of doing things, rather than inventing our own default mechanism.

**Comment by jakehschwartz** [comment]
Thanks for the feedback. Do you mind explaining (or linking to something that explains) how I should be using Git in order to make the plugin work? Just using `git checkout -b new-branch` does not set up a a remote or a merge entry in my `.git/config`, which is what the code uses to determine what it calls `trackingRemote` and `trackingBranch`. Thanks again.

**Comment by jroper** [comment]
If it is a new branch that you've created, then when you push it, run:

    git push -u <remote> [<branch>]

to set the tracking branch.  If the remote branch already exists, and you don't want to push, you can do:

    git branch -u <remote>/<branch>

**Comment by jakehschwartz** [comment]
So it's a bit of a chicken and a egg problem. In my other PR, I've added the ability to checkout new branches, but pushing to them doesn't work because the remote is not set. But to set up the tracking as you described, you have to know the remote you want to use.

**Comment by jakehschwartz** [comment]
I am going to try to merge some of this functionality with my other PR https://github.com/sbt/sbt-release/pull/191

**Pull request closed without merging**
