### PR TITLE
Allow to cut a release when working directory has untracked files

### LINKED ISSUE #40: Working copy is dirty in git
When using git as vcs, "working copy is dirty" error is thrown when the user has untracked files, but no uncommitted changes

### PR DESCRIPTION
**Pull request by avdv**
Fixes #40 

Close #42

### CODE REVIEW

**Comment by jozic** [comment]
how about adding a small section to README describing the new setting?

**Comment by avdv** [comment]
> how about adding a small section to README describing the new setting?

OK, done. WDYT?

**Comment by chammond75** [comment]
Sorry, I'm a total n00b: Where does `releaseIgnoreUntrackedFiles := true` go? I've added it both to my release.sbt and my build.sbt. I just added it as a single line outside of the build sequence. I'm trying to use jenkins to do a release and it keeps failing because of the creation of the Dockerfile during the process. Any guidance would be much appreciated. Thanks in advance.

**Comment by avdv** [comment]
Pay attention to what the message said: there were *modified* files, not *untracked* files. This is a different error.

Why do you commit auto-generated files? Usually, the `target` directory is added to `.gitgnore` to never (accidentially) commit files inside of it.

Just `git rm target/docker/Dockerfile` and you should be good.

**Comment by chammond75** [comment]
Yes! My bad! Thank you for spotting that. And that you for the prompt response. Following your advice has resolved that issue. Now I'm running into some git issue (related to HEAD). But this problem appears to be resolved. If, as I get further, I run into more questions I'll let you know. Again thank you very much!

**Comment by chammond75** [comment]
Well I guess this problem is happening in sbt-release as well. Though it sounds like something is not quite right with my git setup is that right?

[info] Starting release process off commit: 35b4df43764e97a7a25037acc3b6e001014d244d
fatal: ref HEAD is not a symbolic ref
java.lang.RuntimeException: Nonzero exit value: 128
	at scala.sys.package$.error(package.scala:27)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:131)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:101)
	at sbtrelease.Git.currentBranch(Vcs.scala:139)
	at sbtrelease.Git.trackingRemoteCmd$lzycompute(Vcs.scala:134)
	at sbtrelease.Git.trackingRemoteCmd(Vcs.scala:134)
	at sbtrelease.Git.hasUpstream(Vcs.scala:137)
	at sbtrelease.ReleaseStateTransformations$$anonfun$checkUpstream$1.apply(ReleaseExtra.scala:215)
	at sbtrelease.ReleaseStateTransformations$$anonfun$checkUpstream$1.apply(ReleaseExtra.scala:214)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$apply$5.apply(ReleasePlugin.scala:196)
	at sbtrelease.ReleasePlugin$autoImport$ReleaseKeys$$anonfun$5$$anonfun$apply$5.apply(ReleasePlugin.scala:196)

**Pull request merged**
