### PR TITLE
Switched to using auto plugins

### PR DESCRIPTION
**Pull request by jroper**
This is a major refactor. Not much attempt has been made to maintain backwards compatibility, as the sbt conventions have significantly changed, and it's difficult to maintain backwards compatibility and maintain the sbt conventions.

A summary of changes:

* Switch to using auto plugins. The release plugin is now automatically enabled if it is added in plugins.sbt, no need to reference releaseSettings anymore.
* Move all commonly used keys to autoImport, so they are automatically available in build.sbt, instead of needing to import ReleaseKeys._
* Update all key names to sbt 0.13 convention of camel case rather than kebab case.
* Switch to sbt 0.13 convention of naming the Scala keys the same as the key names, using the taskKey/settingKey macros.
* Remove cross sbt build support, there's no way to maintain it with a switch to auto plugins.
* Bump version number to 1.0.0.

### CODE REVIEW

**Comment by gseitz** [comment]
@jroper I don't have much time to look after this project anymore. Would you be interested to take over? There were a few other things I would like to see implemented, but I just don't get around to doing them.

**Comment by gseitz** [comment]
Oh, and this PR looks stellar and the functionality is long overdue. Thanks a lot!

**Comment by jroper** [comment]
I'm happy to take an administrative role, though "take over" sounds like a responsibility that I don't have time to do :) The plugin also needs to be updated to publish to bintray, since the sbt artifactory is now gone. I'm happy to do that, I already have all the access etc.

There's a few other things I want to do too, for example, make it very easy to turn commands and input tasks into release steps. Are you happy with me merging this, making those few other changes, and then publishing a 1.0.0-RC1?

**Comment by gseitz** [comment]
Yes, I understand the time constraints. In any case, the changes you have
in mind sound good. Feel free to merge at your convenience. Thanks.

On Fri, May 8, 2015 at 1:27 AM, James Roper <notifications@github.com>
wrote:

> I'm happy to take an administrative role, though "take over" sounds like a
> responsibility that I don't have time to do :) The plugin also needs to be
> updated to publish to bintray, since the sbt artifactory is now gone. I'm
> happy to do that, I already have all the access etc.
>
> There's a few other things I want to do too, for example, make it very
> easy to turn commands and input tasks into release steps. Are you happy
> with me merging this, making those few other changes, and then publishing a
> 1.0.0-RC1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbt/sbt-release/pull/105#issuecomment-100046008>.
>



-- 
Gerolf Seitz

twitter: @gersei
code: github.com/gseitz

**Pull request merged**
