### PR TITLE
Fix to problem with untracked files stopping release #40

### PR DESCRIPTION
**Pull request by paulmdavies**
Added more thorough check for repo dirtiness when release is called.

Now distinguishes between unstaged changes and untracked files. Untracked files can be ignored by setting 
ignoreUntrackedFiles := true in the project settings, allowing the user to release even if they have untracked files. This setting defaults to false, for compatibility with existing code.

### CODE REVIEW

**Comment by avdv** [comment]
:+1: Thanks @paulmdavies

**Comment by tjadams** [comment]
:+1: sounds like a good change

**Comment by alexbohr** [comment]
Would really love to have this option added, would make this plug-in a better option to git-flow if I didn't have to worry about untracked files for every release.
Thanks

**Comment by paulmdavies** [comment]
@alexbohr it was added. Just specify the ignoreUntrackedFiles key in your sbt configuration.

**Comment by alexbohr** [comment]
Thanks @paulmdavies ... but what version is it released in?  Looks like this pull-request is still open and hasn't been merged in yet.

**Comment by pjolep** [comment]
Is this going to be merged soon?

**Comment by avdv** [comment]
bump. what's the matter? why isn't this merged already?

**Comment by mphuff** [comment]
+1 Where is the merge on this? Would love to have this available :)

**Comment by avdv** [comment]
Since master and this PR diverged quite some time ago, I have rebased the commits onto master, cleaned up the code a bit (to avoid compiler warnings) and implemented the `hasUntrackedFiles` and `hasModifiedFiles` for the Subversion.

Have a look here:

https://github.com/avdv/sbt-release/tree/fix-issue-40

WDYT, should I PR this?

**Comment by paulmdavies** [comment]
I think, @avdv, I'd keep it as your version. I'd thought not more than a coupleof days ago about forking it myself - @gseitz doesn't seem to care for this project any more, so let's have a fork with this merge which is what the people want :-)

**Comment by avdv** [comment]
Yeah, apparently gseitz doesn't care for this project any more. But, since this plugin is community maintained I'm hoping to get this integrated instead of maintaining a separate fork. 

@jroper, you seem to feel responsible for this plugin. What do you think?

**Comment by jroper** [comment]
Responsible?  Hmm... lazy but benevolent person with the necessary access to merge and release is a better description for me.  If a change is simple for me to review (or has been reviewed by others that I trust), I'll merge it and cut a new release, but only if I have enough time and enough people ask :)

Fix the conflicts (or create a new PR) and I'll merge.

**Comment by avdv** [comment]
> Fix the conflicts (or create a new PR) and I'll merge.

Cool, here you are: https://github.com/sbt/sbt-release/issues/144

**Pull request closed without merging**
